-- MySQL Script generated by MySQL Workbench
-- Mon Dec  8 17:32:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema incendios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema incendios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `incendios` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `incendios` ;

-- -----------------------------------------------------
-- Table `incendios`.`dim_agente_causante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incendios`.`dim_agente_causante` (
  `id_causa` INT NOT NULL,
  `descripcion_causa` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion_agente` VARCHAR(45) NULL DEFAULT NULL,
  `es_intencionado` VARCHAR(45) NULL DEFAULT NULL,
  `es_natural` VARCHAR(45) NULL,
  PRIMARY KEY (`id_causa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `incendios`.`dim_clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incendios`.`dim_clima` (
  `id_clima` INT NOT NULL,
  `estacion` VARCHAR(45) NULL,
  `dias_ultima_lluvia` INT NULL,
  `temp_max` INT NULL,
  `hum_relativa` INT NULL,
  `velocidad_de_viento` INT NULL,
  `direccion_de_viento` INT NULL,
  `rango_temp` VARCHAR(45) NULL,
  PRIMARY KEY (`id_clima`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `incendios`.`dim_espacio_protegido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incendios`.`dim_espacio_protegido` (
  `id_espacio_protegido` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `superficie` INT NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `tamano_espacio` INT NULL,
  `es_pequeño` INT NULL,
  `es_mediano` INT NULL,
  `es_grande` INT NULL,
  PRIMARY KEY (`id_espacio_protegido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `incendios`.`dim_fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incendios`.`dim_fecha` (
  `id_fecha` INT NOT NULL,
  `año` INT NULL DEFAULT NULL,
  `es_bisiesto` INT NULL,
  PRIMARY KEY (`id_fecha`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `incendios`.`dim_localizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incendios`.`dim_localizacion` (
  `id_localizacion` INT NOT NULL,
  `comunidad` VARCHAR(45) NULL DEFAULT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  `comarca` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_localizacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `incendios`.`dim_vegetacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incendios`.`dim_vegetacion` (
  `id_tipo_vegetacion` INT NOT NULL,
  `especie` VARCHAR(45) NULL DEFAULT NULL,
  `cod_modelo_combustion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_vegetacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `incendios`.`hecho_incendios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incendios`.`hecho_incendios` (
  `id_pif` INT NOT NULL,
  `id_causa` INT NOT NULL,
  `id_localizacion` INT NOT NULL,
  `id_tipo_vegetacion` INT NOT NULL,
  `id_espacio_protegido` INT NOT NULL,
  `id_fecha` INT NOT NULL,
  `id_clima` INT NOT NULL,
  `total_perdida` INT NOT NULL,
  `superficie_protegida` DECIMAL(10,2) NOT NULL,
  `t_deteccion` DATETIME NOT NULL,
  `t_extension` DATETIME NOT NULL,
  `medios_aereos_desplegados` INT NOT NULL,
  `medios_personal_desplegados` INT NOT NULL,
  `superficie_arbolada_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pif`),
  INDEX `id_causa` (`id_causa` ASC) VISIBLE,
  INDEX `id_localizacion` (`id_localizacion` ASC) VISIBLE,
  INDEX `id_tipo_vegetacion` (`id_tipo_vegetacion` ASC) VISIBLE,
  INDEX `id_espacio_protegido` (`id_espacio_protegido` ASC) VISIBLE,
  INDEX `id_fecha` (`id_fecha` ASC) VISIBLE,
  INDEX `id_clima` (`id_clima` ASC) VISIBLE,
  CONSTRAINT `hecho_incendios_ibfk_1`
    FOREIGN KEY (`id_causa`)
    REFERENCES `incendios`.`dim_agente_causante` (`id_causa`),
  CONSTRAINT `hecho_incendios_ibfk_2`
    FOREIGN KEY (`id_localizacion`)
    REFERENCES `incendios`.`dim_localizacion` (`id_localizacion`),
  CONSTRAINT `hecho_incendios_ibfk_3`
    FOREIGN KEY (`id_tipo_vegetacion`)
    REFERENCES `incendios`.`dim_vegetacion` (`id_tipo_vegetacion`),
  CONSTRAINT `hecho_incendios_ibfk_4`
    FOREIGN KEY (`id_espacio_protegido`)
    REFERENCES `incendios`.`dim_espacio_protegido` (`id_espacio_protegido`),
  CONSTRAINT `hecho_incendios_ibfk_5`
    FOREIGN KEY (`id_fecha`)
    REFERENCES `incendios`.`dim_fecha` (`id_fecha`),
  CONSTRAINT `hecho_incendios_ibfk_6`
    FOREIGN KEY (`id_clima`)
    REFERENCES `incendios`.`dim_clima` (`id_clima`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
